import * as os from 'os';

export const AIMD_VERSION = '1.1';

export interface AIMdContext {
  // ── Identity ────────────────────────────────────────────────────────────────
  version: string;
  created: string;
  updated: string;
  sessionId: string;
  project: string;
  platform: string;
  device: string;
  workspacePath?: string;

  // ── Project metadata (auto-collected) ───────────────────────────────────────
  projectDescription?: string;  // from README / package.json / pyproject.toml etc.
  techStack?: string[];          // detected languages/frameworks
  gitRemote?: string;            // repo URL

  // ── Task (user-set) ─────────────────────────────────────────────────────────
  task: string;
  notes: string;
  nextSteps: string[];

  // ── Live state (auto-collected) ──────────────────────────────────────────────
  openFiles: string[];           // open editor tabs (VS Code) or recently changed (CLI)
  recentFiles?: string[];        // files changed in last 7 days
  gitBranch?: string;
  gitCommits?: string[];         // recent commit one-liners with date
  gitStatusSummary?: string;     // M/A/D/? counts for uncommitted changes
  fileTree?: string;
}

// ─── Serialize ────────────────────────────────────────────────────────────────

export function serialize(ctx: AIMdContext): string {
  const lines: string[] = [];

  // Title
  lines.push(`# AI Context — ${ctx.project}`);
  lines.push('');
  lines.push(`> **Updated:** ${fmt(ctx.updated)}  |  **Platform:** ${ctx.platform}  |  **Device:** ${ctx.device}`);
  lines.push('');
  lines.push('---');
  lines.push('');

  // ── Project Overview ─────────────────────────────────────────────────────────
  lines.push('## Project Overview');
  lines.push('');

  if (ctx.projectDescription) {
    lines.push(ctx.projectDescription);
    lines.push('');
  }

  const overviewRows: [string, string][] = [
    ['Project', `\`${ctx.project}\``],
    ['Platform', ctx.platform],
    ['Device', ctx.device],
    ['Session ID', `\`${ctx.sessionId}\``],
    ['Created', fmt(ctx.created)],
    ['Updated', fmt(ctx.updated)],
    ['AI.md Version', ctx.version],
  ];
  if (ctx.workspacePath) overviewRows.push(['Workspace', `\`${ctx.workspacePath}\``]);
  if (ctx.gitRemote)    overviewRows.push(['Repository', ctx.gitRemote]);
  if (ctx.gitBranch)    overviewRows.push(['Branch', `\`${ctx.gitBranch}\``]);
  if (ctx.techStack?.length) overviewRows.push(['Tech Stack', ctx.techStack.join(', ')]);

  lines.push('| Field | Value |');
  lines.push('|---|---|');
  overviewRows.forEach(([k, v]) => lines.push(`| ${k} | ${v} |`));
  lines.push('');

  // ── Current Task ─────────────────────────────────────────────────────────────
  if (ctx.task) {
    lines.push('## Current Task');
    lines.push('');
    lines.push(ctx.task);
    lines.push('');
  }

  // ── Context Notes ────────────────────────────────────────────────────────────
  if (ctx.notes) {
    lines.push('## Context Notes');
    lines.push('');
    lines.push(ctx.notes);
    lines.push('');
  }

  // ── Next Steps ───────────────────────────────────────────────────────────────
  if (ctx.nextSteps.length > 0) {
    lines.push('## Next Steps');
    lines.push('');
    ctx.nextSteps.forEach((s, i) => lines.push(`${i + 1}. ${s}`));
    lines.push('');
  }

  // ── Recent Git Activity ──────────────────────────────────────────────────────
  if (ctx.gitCommits?.length) {
    lines.push('## Recent Git Activity');
    lines.push('');
    if (ctx.gitBranch) lines.push(`**Branch:** \`${ctx.gitBranch}\``);
    if (ctx.gitStatusSummary) lines.push(`**Uncommitted:** ${ctx.gitStatusSummary}`);
    lines.push('');
    ctx.gitCommits.forEach(c => lines.push(`- ${c}`));
    lines.push('');
  }

  // ── Open / Active Files ──────────────────────────────────────────────────────
  if (ctx.openFiles.length > 0) {
    lines.push('## Open / Active Files');
    lines.push('');
    ctx.openFiles.forEach(f => lines.push(`- \`${f}\``));
    lines.push('');
  }

  // ── Recently Changed Files ───────────────────────────────────────────────────
  if (ctx.recentFiles?.length) {
    lines.push('## Recently Changed Files (last 7 days)');
    lines.push('');
    ctx.recentFiles.forEach(f => lines.push(`- \`${f}\``));
    lines.push('');
  }

  // ── File Tree ────────────────────────────────────────────────────────────────
  if (ctx.fileTree) {
    lines.push('## Project Structure');
    lines.push('');
    lines.push('```');
    lines.push(ctx.fileTree);
    lines.push('```');
    lines.push('');
  }

  lines.push('---');
  lines.push('');
  lines.push('*Generated by [AI.md](https://github.com/ai-md/vscode-extension) — Cross-platform AI context continuity*');

  return lines.join('\n');
}

// ─── Parse ────────────────────────────────────────────────────────────────────

export function parse(content: string): Partial<AIMdContext> {
  const ctx: Partial<AIMdContext> = {};

  const grab = (pattern: RegExp) => {
    const m = content.match(pattern);
    return m ? m[1].trim() : undefined;
  };

  const section = (heading: string) => {
    const re = new RegExp(`## ${heading}\\n\\n([\\s\\S]+?)(?=\\n## |\\n---\\n|\\n*$)`);
    const m = content.match(re);
    return m ? m[1].trim() : undefined;
  };

  ctx.project = grab(/^# AI Context[—\-–]+\s*(.+)$/m);
  ctx.task    = section('Current Task');
  ctx.notes   = section('Context Notes');
  ctx.platform = grab(/\| Platform \| ([^|]+) \|/);
  ctx.device   = grab(/\| Device \| ([^|]+) \|/);
  ctx.updated  = grab(/\| Updated \| ([^|]+) \|/);
  ctx.created  = grab(/\| Created \| ([^|]+) \|/);
  ctx.sessionId = grab(/\| Session ID \| `?([^`|]+)`? \|/);
  ctx.gitBranch = grab(/\*\*Branch:\*\* `([^`]+)`/) ?? grab(/\| Branch \| `([^`]+)` \|/);
  ctx.gitRemote = grab(/\| Repository \| ([^|]+) \|/);

  const wp = grab(/\| Workspace \| `?([^`|]+)`? \|/);
  if (wp) ctx.workspacePath = wp;

  const nextRaw = section('Next Steps');
  if (nextRaw) {
    ctx.nextSteps = nextRaw
      .split('\n').filter(l => /^\d+\./.test(l))
      .map(l => l.replace(/^\d+\.\s*/, ''));
  }

  const openRaw = section('Open / Active Files') ?? section('Open Files');
  if (openRaw) {
    ctx.openFiles = openRaw.split('\n')
      .filter(l => l.startsWith('- ')).map(l => l.replace(/^- `?/, '').replace(/`?$/, ''));
  }

  return ctx;
}

// ─── Resume Prompt ────────────────────────────────────────────────────────────

export function generateResumePrompt(aimdContent: string): string {
  const ctx = parse(aimdContent);
  const project = ctx.project ? `the **${ctx.project}** project` : 'my project';
  const platform = ctx.platform ?? 'an AI assistant';

  const taskLine = ctx.task
    ? `My current task: **${ctx.task}**`
    : 'My current task is described in the context file below.';

  const stepsLine = ctx.nextSteps?.length
    ? `\n\nMy planned next steps:\n${ctx.nextSteps.map((s, i) => `${i + 1}. ${s}`).join('\n')}`
    : '';

  return `I'm resuming work on ${project}. I was previously working with ${platform} and need to continue here.

Below is my AI.md context file capturing everything about this work:

---
${aimdContent}
---

${taskLine}${stepsLine}

Please review this context and help me continue seamlessly from where I left off. Ask any clarifying questions before we begin.`;
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

function fmt(iso: string): string {
  try {
    const d = new Date(iso);
    return `${d.toLocaleDateString()} ${d.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}`;
  } catch {
    return iso;
  }
}

export function newSessionId(): string {
  return `${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 7)}`;
}

export function deviceName(): string {
  return os.hostname();
}
