package com.aimd

import com.intellij.openapi.actionSystem.AnAction
import com.intellij.openapi.actionSystem.AnActionEvent
import com.intellij.openapi.project.Project
import com.intellij.openapi.ui.Messages
import com.intellij.openapi.vfs.VirtualFile
import git4idea.repo.GitRepositoryManager
import java.io.File
import java.time.Instant

/**
 * AI.md Save Context action — captures project state into a .ai.md file.
 *
 * Gathers: git branch, recent commits, modified files, open editor tabs,
 * project tech stack (detected from config files), and writes a structured
 * markdown document.
 */
class AiMdSaveAction : AnAction() {

    override fun actionPerformed(e: AnActionEvent) {
        val project = e.project ?: return

        val context = buildContext(project)
        val settings = AiMdSettings.getInstance()
        val filename = settings.projectName.ifBlank { "ai" } + ".ai.md"

        // Save locally
        val basePath = project.basePath ?: return
        val file = File(basePath, filename)
        file.writeText(context)

        // Sync to cloud if configured
        if (settings.githubToken.isNotBlank()) {
            try {
                GistSync.save(settings.githubToken, settings.gistId, filename, context) { newId ->
                    settings.gistId = newId
                }
                Messages.showInfoMessage(project, "Context saved and synced to Gist", "AI.md")
            } catch (ex: Exception) {
                Messages.showWarningDialog(project, "Saved locally but sync failed: ${ex.message}", "AI.md")
            }
        } else {
            Messages.showInfoMessage(project, "Context saved to $filename", "AI.md")
        }
    }

    private fun buildContext(project: Project): String {
        val sb = StringBuilder()
        val now = Instant.now().toString()
        val name = project.name

        sb.appendLine("# AI Context — $name")
        sb.appendLine()
        sb.appendLine("> **Updated:** $now  |  **IDE:** JetBrains")
        sb.appendLine()
        sb.appendLine("---")
        sb.appendLine()

        // Git info
        val repos = GitRepositoryManager.getInstance(project).repositories
        if (repos.isNotEmpty()) {
            val repo = repos.first()
            sb.appendLine("## Git")
            sb.appendLine("- **Branch:** ${repo.currentBranch?.name ?: "detached"}")
            sb.appendLine("- **Remote:** ${repo.remotes.firstOrNull()?.firstUrl ?: "none"}")
            sb.appendLine()

            // Recent commits (last 5)
            sb.appendLine("### Recent Commits")
            // Note: full git log reading requires Git4Idea API calls
            sb.appendLine("*(Run `git log --oneline -5` for latest)*")
            sb.appendLine()
        }

        // Open files
        val fileEditorManager = com.intellij.openapi.fileEditor.FileEditorManager.getInstance(project)
        val openFiles = fileEditorManager.openFiles.toList()
        if (openFiles.isNotEmpty()) {
            sb.appendLine("## Open Files")
            openFiles.forEach { vf: VirtualFile ->
                val rel = project.basePath?.let { vf.path.removePrefix(it) } ?: vf.name
                sb.appendLine("- `$rel`")
            }
            sb.appendLine()
        }

        // Tech stack detection
        val basePath = project.basePath
        if (basePath != null) {
            val techStack = detectTechStack(File(basePath))
            if (techStack.isNotEmpty()) {
                sb.appendLine("## Tech Stack")
                techStack.forEach { sb.appendLine("- $it") }
                sb.appendLine()
            }
        }

        sb.appendLine("---")
        sb.appendLine()
        sb.appendLine("*Generated by AI.md JetBrains Plugin*")

        return sb.toString()
    }

    private fun detectTechStack(root: File): List<String> {
        val stack = mutableListOf<String>()
        val checks = mapOf(
            "package.json" to "Node.js / npm",
            "tsconfig.json" to "TypeScript",
            "build.gradle.kts" to "Gradle (Kotlin DSL)",
            "build.gradle" to "Gradle",
            "pom.xml" to "Maven / Java",
            "Cargo.toml" to "Rust / Cargo",
            "go.mod" to "Go",
            "requirements.txt" to "Python",
            "pyproject.toml" to "Python (modern)",
            "Gemfile" to "Ruby / Bundler",
            "composer.json" to "PHP / Composer",
            "Dockerfile" to "Docker",
            ".github/workflows" to "GitHub Actions CI",
        )
        checks.forEach { (file, tech) ->
            if (File(root, file).exists()) stack.add(tech)
        }
        return stack
    }
}
